listening-port=443
min-port=49152
max-port=65535

fingerprint
lt-cred-mech
user=janus:topsecret
realm=webrtc-lab

listening-ip=192.168.122.55
listening-ip=198.51.100.20

external-ip=198.51.100.20/192.168.122.55

no-tls
no-dtls
no-tcp

verbose
simple-log


max-allocate-lifetime=86400
stale-nonce=600
